import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
const rubik = Rubik({ subsets: ["latin"], variable: "--font-rubik" });
import SessionProvider from "./components/SessionProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={rubik.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
